version: '3'

services:
  sql_server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: root
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password123
    ports:
      - "1433:1433"
    volumes:
      - sql-server:/var/opt/mssql/data

volumes:
  sql-server: